// <auto-generated />
using System;
using Duovie.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Duovie.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DuovieDbContext))]
    [Migration("20260822102935_AddParticipantSessions")]
    partial class AddParticipantSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Duovie.Domain.Rooms.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GuestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("Rooms", null, t =>
                        {
                            t.HasCheckConstraint("CK_Room_DistinctParticipants", "\"GuestId\" IS NULL OR \"GuestId\" <> \"HostId\"");

                            t.HasCheckConstraint("CK_Room_ExpirationAfterCreation", "\"ExpiresAtUtc\" > \"CreatedAtUtc\"");

                            t.HasCheckConstraint("CK_Room_ValidStatus", "\"Status\" IN ('WaitingForGuest', 'Ready', 'Closed')");
                        });
                });

            modelBuilder.Entity("Duovie.Infrastructure.Persistence.Entities.ParticipantSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("RoomId", "ParticipantId")
                        .IsUnique();

                    b.HasIndex("RoomId", "Role")
                        .IsUnique();

                    b.ToTable("ParticipantSessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_ParticipantSession_ExpirationAfterIssue", "\"ExpiresAtUtc\" > \"IssuedAtUtc\"");

                            t.HasCheckConstraint("CK_ParticipantSession_TokenHashLength", "octet_length(\"TokenHash\") = 32");

                            t.HasCheckConstraint("CK_ParticipantSession_ValidRole", "\"Role\" IN ('Host', 'Guest')");
                        });
                });

            modelBuilder.Entity("Duovie.Infrastructure.Persistence.Entities.ParticipantSessionEntity", b =>
                {
                    b.HasOne("Duovie.Domain.Rooms.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
